### ISSUE TITLE
Please install dotnet core to enable automatic generation of Html report. - Ubuntu 16.04

### ISSUE THREAD

**Issue by basickarl** [MicrosoftDocs/azure-devops-docs#4639]
Page: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript?view=azure-devops#publish-code-coverage-results

Hi. I've trying to publish code coverage reports via istanbul and cobertura. I get a warning in my pipeline:

```
##[debug]Agent.TempDirectory=/azp/agent/_work/_temp
##[debug]Generating Html Report using ReportGenerator: /azp/agent/_work/_temp/cchtml
##[debug]which 'dotnet'
##[debug]not found
##[warning]Please install dotnet core to enable automatic generation of Html report.
##[debug]Processed: ##vso[task.issue type=warning;]Please install dotnet core to enable automatic generation of Html report.
```

My User Agent is using the OS Ubuntu 16.04. It would perhaps be a good idea to update the documentation to express that .NET Core is a requirement.

**Comment by AnticliMaxtic** [comment]
I'm seeing the same issue, but I am not able to use the "UseDotNet@2" task to install .net core, it fails 
```
Tool to install: .NET Core runtime version 3.x.
Found version 3.1.0 in channel 3.1 for user specified version spec: 3.x
Version: 3.1.0 was found in cache.
Creating global tool path and pre-pending to PATH.
Installing NuGet version 4.4.1
Found tool in cache: NuGet 4.4.1 x64
##[warning]Can\'t find loc string for key: Info_ResolvedToolFromCache
Info_ResolvedToolFromCache 4.4.1
##[warning]Can\'t find loc string for key: Info_UsingVersion
Info_UsingVersion 4.4.1
Found tool in cache: NuGet 4.4.1 x64
##[warning]Can\'t find loc string for key: Info_UsingToolPath
Info_UsingToolPath /azp/agent/_work/_tool/NuGet/4.4.1/x64
Prepending PATH environment variable with directory: /azp/agent/_work/_tool/NuGet/4.4.1/x64
Setting up proxy configuration for NuGet.
##[error]Failed while installing NuGet version. Error: 4.4.1 Parameter 'toolPath' cannot be null or empty.
```

**Comment by jsblock78** [comment]
@AnticliMaxtic I have added an issue for the issue you are describing:

https://github.com/microsoft/azure-pipelines-tasks/issues/12343

**Comment by fvanwijk** [comment]
Any progress on this?
I'm using Linux docker container and it keeps showing the warning.
"Use DotNet Core" tasks is added.  I tried both default and version 2.2.3.

As workaround I provide the HTML report myself (`jest --coverage --coverageReporters=html`) but the CSS is not loading/working without converting to inline styles first and the warning still appears. I don't know how to suppress this warning.

**Comment by luismachaner** [comment]
@basickarl did you manage to solve it? I find the same when running tests on a docker container and I still don't know what's missing. I tried with dotnet and node together to no avail.... See dockerfile:

```
FROM mcr.microsoft.com/dotnet/core/sdk:3.1-alpine


## Non glibc-based container
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops#non-glibc-based-containers

# Azure pipelines requires common admin packages: bash, sudo and shadow
RUN apk add --no-cache --virtual .pipeline-deps readline linux-pam \
  && apk add bash sudo shadow \
  && apk del .pipeline-deps


# Alpine Linux does not use glibc, so we are providing our own node and we must tell the agent where to finde Node.js
LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/local/bin/node"

## Dockerization
# Install npm (depends on nodejs)
RUN apk add --update \
        npm \
  && rm -rf /var/cache/apk/*

# Config Chromium
ENV CHROME_BIN=/usr/bin/chromium-browser
ENV CHROME_PATH=/usr/lib/chromium/
```

**Comment by luismachaner** [comment]
After some hours, I've tried the same Dockerfile (except for an error in the node path, that I have fixed in the original post). Now it works... I cannot explain it, because I am pretty sure that the same Dockerfile gave me that error.
Also, I've tested with the runtime image (mcr.microsoft.com/dotnet/core/runtime:3.1-alpine), so no SDK is necessary

**Comment by cxwtool** [comment]
This issue hasn't been updated in more than 180 days, so we've closed it. If you feel the issue is still relevant and needs fixed, please reopen it and we'll take another look. We appreciate your feedback and apologize for any inconvenience.

**Comment by edag94** [comment]
Reopening this issue as I am also getting this issue. I then proceeded to add a UseDotnet task:

```yaml
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 2.2.203
    installationPath: $(Agent.ToolsDirectory)/dotnet
```

On the subsequent run, I get this log:

```text
FailFast:
Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.

   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomain.InitializeCompatibilityFlags()
   at System.AppDomain.Setup(System.Object)
##[warning]Failed to generate Html report. Error: null
```

I'm not sure what to do with this message. I have tried different versions of the SDK, with no luck.

**Comment by cforce** [comment]
Actually this dotnet tools is used under the covers to create the reports
https://github.com/danielpalme/ReportGenerator/
The question is, is it enough to in .net runtime to your worker pool where you run the CI jobs.

docker extracted
```
# Install .NET CORE
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
# just runtime
RUN sudo dpkg -i packages-microsoft-prod.deb
# runtime(only)
RUN sudo apt install dotnet-runtime-3.1
# sdk
#RUN sudo apt-get install -y dotnet-sdk-5.0

```

**Comment by Samuel-Beslogic** [comment]
> Any progress on this? I'm using Linux docker container and it keeps showing the warning. "Use DotNet Core" tasks is added. I tried both default and version 2.2.3.
> 
> As workaround I provide the HTML report myself (`jest --coverage --coverageReporters=html`) but the CSS is not loading/working without converting to inline styles first and the warning still appears. I don't know how to suppress this warning.

For the missing CSS, see [this post](https://davidsekar.com/aspnetcore/code-coverage-html-reports-are-missing-styles-in-vsts) for an explanation and solution (using the [`vsts-coverage-styles`](https://www.npmjs.com/package/vsts-coverage-styles) package)
For the warning still present. Move to this issue: https://github.com/microsoft/azure-pipelines-tasks/issues/16084

**Comment by rsarrazin2** [comment]
I faced the original issue with a Ubuntu-20.04-based container (for your reference: `mcr.microsoft.com/vscode/devcontainers/base:0-focal`). Using the task `UseDotNet@2` didn't help - probably because it installs `dotnet` onto the agent, and not into the container.

I solved this with the following addition to the `Dockerfile` used to build the container image similar to [@cforce's comment](https://github.com/MicrosoftDocs/azure-devops-docs/issues/4639#issuecomment-832148815) based on [Install the .NET SDK or the .NET Runtime on Ubuntu
](https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2004):
```Dockerfile
RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && sudo dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends dotnet-runtime-6.0
```

**Comment by HDLP9** [comment]
My fix was using the UseDotNet@2 before the PublishCodeCoverageResults. Like this:

```
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 7.0.x'
  inputs:
    version: 7.0.x
- task: PublishCodeCoverageResults@2
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: $(Build.SourcesDirectory)/tmp/coverage/coverage.xml
    reportDirectory: $(Build.SourcesDirectory)/tmp/coverage
```

but this requires us to install .NET Core just for reporting.
