### ISSUE TITLE
Variable group yaml variable expression in Azure Devops Pipeline

### ISSUE THREAD

**Issue by Repcak** [MicrosoftDocs/azure-devops-docs#7586]
I'm having difficulties with variable expression with the AzureKeyVault task. Both the azureSubscription and KeyVaultName values expressions are not being resolved to have variables in a variable Group. It works if I define those variables manually in any way in the yaml. Either in azure-pipelines.yml or in the template variables_test.yml that I import at the beginning of the stage.

I read in the documentation, that variables from a variable group should be used like this $(var) but then it throws an error saying a subscription like '$(var)' does not exist. 

Template:
azure-pipelines.yml:

```
- stage: Test

  variables:
  - template: variables_Test.yml  # Template reference
  - group: testVariableGroup

  dependsOn: []

  jobs:

  - job: Test
    
    steps:

    - task: AzureKeyVault@1
      inputs:
        azureSubscription: ${{ variables.spn_kv_app }} # Service connection Name
        KeyVaultName: ${{ variables.keyVaultName }}
        SecretsFilter: '*'
```

In the logs from the staging i can see the variables being set from the variable group:
```
Job preparation parameters
Variables:
  keyVaultName: $[ variablegroups.testVariableGroup.keyVaultName ]
  resourceGroupName: $[ variablegroups.testVariableGroup.resourceGroupName ]
  spn_cd_app: $[ variablegroups.testVariableGroup.spn_cd_app ]
  spn_kv_app: $[ variablegroups.testVariableGroup.spn_kv_app ]
  storageAccountName: $[ variablegroups.testVariableGroup.storageAccountName ]
```
One thing to note that those variables are not set to secrets in the variable group.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd7e0bd3-1f7d-d7b6-cc72-5ef63c31b46a
* Version Independent ID: dae87abd-b73d-9120-bcdb-6097d4b40f2a
* Content: [Define variables - Azure Pipelines](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#feedback)
* Content Source: [docs/pipelines/process/variables.md](https://github.com/MicrosoftDocs/vsts-docs/blob/master/docs/pipelines/process/variables.md)
* Product: **devops**
* Technology: **devops-cicd-process**
* GitHub Login: @juliakm
* Microsoft Alias: **jukullam**

**Comment by Repcak** [comment]
https://stackoverflow.com/questions/60643142/variable-group-yaml-variable-expression-in-azure-devops-pipeline
So someone showed me a solution. So it seems like it works when importing the variable group in the main context but not in the stage context.

**Comment by juliakm** [comment]
@Repcak You should be able to specify a variable at the pipeline, stage, or job level. One issue is that in `azure-pipelines.yml` you are both assigning the group and using a template. You would just want to do one of those things. 

I've put together a simplified YAML that is working but please feel free to also reach out to the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) if you think you have found a bug. 

Here's an example that worked for me. I'll add a modified version of this to the docs.

variables_test.yml
```
variables:
  - group: testVariableGroup
```

azure-pipeline.yml
```
stages:
- stage: MyStage
  variables:
  - template: variables_test.yml
  jobs:
  - job: Test
    steps:
    - script: echo $(keyVaultName)
    - script: echo $(resourceGroupName)
    - script: echo $(storageAccountName)
```

**Comment by Repcak** [comment]
Okey, makes sens. But now I cannot define anyother variablesin the variables_test.yml?

For example:
```
variables:
  - group: testVariableGroup
  someVariableName: someValue
```

**Comment by Repcak** [comment]
Okey, so this anyways does not solve my problem. Script echo as a task works. It does not work however on the AzureSubscription which excepts a service connection endpoint. Try it with any task that needs a AzureSubscription endpoint. 

This behaves wierdly. Because if the group would be imported on the main level. It would be resolved. However if imported on a stage level. It cannot resolve the service connection name like in the screenshot above i've posted.

**Comment by juliakm** [comment]
Thanks for the clarification @Repcak. It sounds like this is a functionality problem with the task. The [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html) is the right place to address it so I'm closing this issue for now.

**Comment by tomkuijsten** [comment]
This is exactly my problem and still doesn't work. Very annoying because no where in the docs there is a reference that the group import of variables only works on root level! Please, update the docs with a warning, this just took 8 hours of my time.

**Comment by juliakm** [comment]
@tomkuijsten  Thanks for pointing this out. I'm adding a note that this should be at the root level.

**Comment by tomkuijsten** [comment]
@juliakm But this is a bug, right? Would be good to document it in the meantime, but it should be fixed. I want to have different variable groups for each stage, that's impossible now.

**Comment by tomkuijsten** [comment]
@juliakm and is there a timeline for an actual fix? I want to use different variable groups for each stage, but that seems to be impossible now.

**Comment by tomkuijsten** [comment]
@juliakm any update?

**Comment by patdaman** [comment]
i am having the same issue, cannot make the service connection a variable.  a different pipeline and file commit is required for me right now for each combinations of service endpoints.  Unsustainable in the long run.

**Comment by Fl4v** [comment]
I have the same problem, when will a fix be issued???

**Comment by juliakm** [comment]
@tomkuijsten and @Fl4v Unfortunately, I don't have updates on product development. Your best bet is to follow-up in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

**Comment by ElkRom** [comment]
Please add fix ASAP

**Comment by IuliiaBabych** [comment]
why is it closed? I don't think i have been fixed..

**Comment by sahalsaad** [comment]
Why this ticket is closed when the issue is still there? Is there any workaround for this issue?

**Comment by sahalsaad** [comment]
Why this issue closed? Is there any workaround for this issue?

**Comment by tomkuijsten** [comment]
> @tomkuijsten and @Fl4v Unfortunately, I don't have updates on product development. Your best bet is to follow-up in the [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

And then end up at another github issue? This is clearly a big bug, I don't understand that you want people's input, but then redirect me to another page to create another issue and pray for the best.

**Comment by mildsar** [comment]
Because of this issue, tt is not possible to implement multistage deployment without this functionality, unless I hardcode variables for every stage. Please add fix ASAP.

**Comment by albpal** [comment]
Same here. I would like to use different groups variables per stage/environment

**Comment by dagtveit** [comment]
Pheeew luckily i found this post quite quickly. completly agree that this needs to be fixed asap

**Comment by dagtveit** [comment]
but it seem to be working on job lvl.

**Comment by albpal** [comment]
Another place where group variables are not properly managed is when downloading a secret file. The name couldn't be a group variable defined on the stage. Very annoying if you split your deployments like 1 stage -> 1 environment and use different credential files depending on a name defined in the group variable.

**Comment by ericchansen** [comment]
This shouldn't be closed. It's a real issue.

Here's another example of this problem in action https://stackoverflow.com/questions/60917078/azure-pipelines-yaml-error-when-using-variable-group-for-deploy-web-app-azur.

**Comment by MichalKosowski** [comment]
yeah, +1 from me for fixing this issue. This is quite a major bug in my opinion...

**Comment by TechnologyAnimal** [comment]
I am echoing the comments everyone else is making in this thread.  **THIS IS A BUG AND SHOULD BE FIXED!**  Why are we getting punted over to "engage the development community"?  No one wants to add a bunch of silly workarounds across thousands of pipelines to solve something that should be fixed by Microsoft.

**Comment by perosb** [comment]
Since this issue tracker is for documentation, who can take this further to the product team @juliakm?

This clearly is unwanted behavior and without proper support for groups at stage level, I don't see how multiple deployments/environment can be used?
Especially if you need to do variable replacement etc in the templates.

**Comment by BalintKorcsmar629** [comment]
I have a very similar issue. I want to set the environment name from a variable group defined in the stage level. The variable does not get resolved. The result of the pipeline run is that a new environment is created with the name $(environmentName). Then the build fails because no matching tag is found in this new "empty" environment (not a big surprise).

**Comment by 00Fede** [comment]
This is still happening. I have a reference to two variable-groups in a stage defined in the root pipeline. When trying to resolve the service-connection `AWS_SERVICE_CONNECTION` variable (defined in variable-group1) in one of the jobs defined in a template, the variable is not resolved. 

        stages: 
       - stage: STAGE_1
         jobs:
         - template: ./template/template1.yaml 
         variables:  
         - group: variable-group1
         - group: variable-group2

./template/template1.yaml 

    jobs:
        - job: job1
     variables:
     steps:         
        - template: ./template2.yaml
          parameters:
            account:  $(AWS_SERVICE_CONNECTION) # THIS IS NOT RESOLVED
./template2.yaml

    steps:
        - task: AWSShellScript@1
          inputs:
            awsCredentials: '${{ parameters.account}}'    #this is resolved literally as $(AWS_SERVICE_CONNECTION)
            regionName: 'us-east-1'
            scriptType: 'inline'
            inlineScript: |
             ... aws CLI scripts

I thought this behaviour was because of the chain of templates, but reading this ticket it seems the variables resolves differently when it becomes to service connection. This must be noted in documentation. 
The only way I made this work is setting a main variable with the value taken from the variable of the library... This breaks the naturality of the pipeline and sum complexity.

**Comment by teom10** [comment]
same issue here, I'm not able to use the variable group and assign a parameter template, variable group $(AzureConnection) is not resolved:

Job Step  input azureSubscription references service connection $(AzureConnection) which could not be found

**Comment by hpettenuci** [comment]
Same issue here! The job step doesn't resolved the variable to assign a template parameter

**Comment by spikemariodiplomado** [comment]
wow, this issue is very interesting. Only works for me if you named the variable as "subscription" and of course using $(subscription). But I tried changing the name of the variable in the library/group and the result was:

- result for the first attempt: azureSubscription references service connection $(ocaio-subscription) which could not be found.
- result for the second attempt: azureSubscription references service connection $(subscription-ocaio) which could not be found.

**Comment by Biptor** [comment]
wow, this issue is very interesting. Only works for me if you named the variable as "subscription" and of course using $(subscription). But I tried changing the name of the variable in the library/group and the result was:

- result for the first attempt: azureSubscription references service connection $(ocaio-subscription) which could not be found.
- result for the second attempt: azureSubscription references service connection $(subscription-ocaio) which could not be found.

(I going to stop to follow the other account spikemariodiplomado)

**Comment by Biptor** [comment]
wow, this issue is very interesting. Even in the stage level works for this variable sql-server-name that comes from the variable group, but not for one that I named subscription-api that I use to set the azureSubscription

My workaround was to define the variable subscription-api in a variables file

variables_dev.yml
```
variables:
- name: subscription-api
  value: az-subscription-dev
```

azure-pipeline.yml
```
- stage: dev
  variables:
  - template: ./variables-dev.yml
  jobs:
  - template: pipeline-templates/job-deploy.yml
    parameters:
      subscription: ${{variables.subscription-api}}
```

I hope that this could be helpful

**Comment by furyd** [comment]
I hit this yesterday - you can use variable groups at the _root_ in order to populate azureSubscription, but not further down in scope, which is a PITA when scoping variable groups for re-use.

You _can_ use parameters though, so the workaround I'm using is to have a variable group at root with keys such as "arm._productname_._environmentname_._propertyname_

I can then pass this down to my templates:

```
parameters:
  - name: locale
    type: string
  - name: product
    type: string

  - name: environments
    type: object
    default:
      - DEV
      - QA
  - name: templates
    type: object
    default:
      - test.template.deploy.yaml
stages:
  - ${{ each environment in parameters.environments }}:
    - ${{ each template in parameters.templates }}:
      - template: templates/${{ template }}
        parameters:
          product: ${{ parameters.product }}
          locale: ${{ parameters.locale }}
          environment: ${{ environment }}
          buildServer: $(arm.${{ parameters.product }}.${{ environment }}.buildServer)
          connection: $(arm.${{ parameters.product }}.${{ environment }}.connection)
```

Then the relevant bits of the template:

```
parameters:
  - name: product
    type: string
  - name: locale
    type: string
  - name: environment
    type: string
  - name: buildServer
    type: string
  - name: connection
    type: string
```

```
            steps:
                - task: AzureWebApp@1
                  displayName: Publish Additional Claims API
                  inputs:
                    azureSubscription: ${{ parameters.connection }}
                    appType: webApp
                    appName: MyApp
```

After spending most of yesterday finding workarounds, I hope this saves someone some time, effort and stress levels!

**Comment by marcelovital** [comment]
I don't think this is a bug, but rather a product limitation. There are two kinds of fields you can't assign "external" (AKA from a var group) variables:
- The ones that point to **Service Connections**, used in many different types of tasks, such as an ARM Template Deployment. (may have many different names depending on the task, such as "azureSubscription", "serviceConnection", etc)
- The **environment** names, mandatory in in deployment jobs

This is actually documented, but in a very hidden place (should be on the main variables page!). See the last paragraph [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline).

You may say _"But I used this in situation XYZ and it worked!"_ and I will agree with you, but that is very unpredictable, depends on the type of task. As a rule of thumb, I never use service connections and environments in variable groups.

**But a workaround exists!** Instead of using vargroups, you can use variables with static values in your main pipeline (which can later call as many templates as you like) or even use a "variable file" that will work just like an variable group, an external yaml template that contains those variables and its values. So, by doing this, you can keep these parameters in a single place, without having to look for them on every pipelines and templates in your solution.

Here's the most basic example:

**main_pipeline.yml:**
```
variables:
  - service_connection: my-service-connection-name
  - environment: Production

jobs:
  - deployment: JOB_DEPLOY
    environment: ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzurePowerShell@5
              inputs:
                azureSubscription: '${{ variables.service_connection }}'
                ScriptType: 'FilePath'
                ScriptPath: '$(Build.Repository.LocalPath)/my_script.ps1'
```

You could also point to an external variable template:

**main_pipeline.yml:**
```
variables:
  - template: project-settings.yml@self

jobs:
  - deployment: JOB_DEPLOY
    environment: ${{ variables.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: AzurePowerShell@5
              inputs:
                azureSubscription: '${{ variables.service_connection }}'
                ScriptType: 'FilePath'
                ScriptPath: '$(Build.Repository.LocalPath)/my_script.ps1'
```

**project-settings.yml:**
```
variables:
  - name: service_connection
    value: my-service-connection-name
  - name: environment
    value: Production
```

Both examples will work the same way. 
The important thing is to have the static values in a file, and use what is called "template expression" syntax (the `${{ }}`).
The reason for this is because template expressions get processed **before** running the pipeline, and at that time, only static values are available to the system. This makes those service connections and environments be able to get values for the variables at the time they need it.

**Comment by karl-barbour** [comment]
This is still a real issue. I use variable files for multi-stage (i.e. environments) pipelines, but I want to store secrets in variable groups (thus not in plaintext in my source control).

Nothing I have tried will let me pass a variable group through to a stage's template.

**Comment by cadsjo** [comment]
Still no solution? Should be really helpful...

**Comment by guilhermepozo** [comment]
Im trying to "select" the var-group according with the "if" condition, but its still not resolving env var :/
